version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:5432/
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - jsguru
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - jsguru
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  jsguru:
    driver: bridge